Change the structure of the homepage and navbar
acf-sack/sack-site pull request #183
Opened 2021-02-05 07:01 UTC by sathsarabandaraj

## Purpose
The purpose of this PR is to fix #182 

## Goals
Modify the structure of the homepage and navbar.

## Approach

- Add some cards to the main section.
- Add more links to the nav-bar.
- Add the Call us button to the nav-bar

### Screenshots
![image](https://user-images.githubusercontent.com/62067185/107000216-8434fb80-67ad-11eb-8c07-4b2de6c790fc.png)

  
### Preview Link

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs

## Test environment
>OS - Ubuntu 20.10 (Groovy Gorilla)
>Browser - Google Chromium 88.0.4324.96 (Official Build) snap (64-bit)

## Learning

2021-02-05 13:05 UTC, Gimhan-minion reviewed
Awesome Job @sathsarabandaraj 💯❤️. There are some minor changes requested. Fix them and we'll get this merged ASAP :)

2021-02-05 13:05 UTC, Gimhan-minion commented on assets/css/material-kit.css
> +  border-top: 3px solid rgba(128, 0, 0, 0.774);
Let's create a custom class instead of directly changing the material CSS file. Or is it Okay to directly change this file @jayasanka-sack WDYT?

2021-02-05 13:05 UTC, Gimhan-minion commented on assets/css/material-kit.css
> -  background: #ffffff;
You can do the same in here too

2021-02-05 13:05 UTC, Gimhan-minion commented on index.html
> +</html>
Add a new line here too

2021-02-05 15:09 UTC, kumuditha-udayanga commented
Great work @sathsarabandaraj! Please do the minor changes, and also squash your commits ``` git rebase -i HEAD~5 ```

2021-02-05 15:11 UTC, kumuditha-udayanga requested changes
Please do the minor changes, and also squash your commits ``` git rebase -i HEAD~5 ```

2021-02-06 05:56 UTC, kumuditha-udayanga approved these changes
Well Done @sathsarabandaraj 🎉

2021-02-06 06:38 UTC, Gimhan-minion approved these changes
Good Job @sathsarabandaraj :100:

2021-02-06 06:38 UTC, merged