Implement the template for societies
acf-sack/sack-site pull request #188
Opened 2021-02-07 07:02 UTC by sathsarabandaraj

## Purpose

The purpose of this PR is to fix #187 

## Goals

## Approach

### Screenshots

 
![screenshot-127-0-0-1-4000-societies-acf-index-html-1612678287399](https://user-images.githubusercontent.com/62067185/107139323-5df39500-6940-11eb-95be-edf870372261.png)

![screenshot-127-0-0-1-4000-societies-template-index-html-1612678308620](https://user-images.githubusercontent.com/62067185/107139319-53390000-6940-11eb-9fa6-f800a9b6bb4f.png)

### Preview Link
https://sathsarabandaraj.github.io/sack-site/societies/acf/index.html
https://sathsarabandaraj.github.io/sack-site/societies/template/index.html

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2021-02-07 11:43 UTC, jayasanka-sack reviewed
Good job @sathsarabandaraj !

suggestions:

- Remove that transparent thing.
- Add facebook iframe to the feed instead of cads. 
- Add a half size header ex: https://demos.creative-tim.com/material-kit/examples/profile-page.html
- Better if we could remove the green color tabs and add them in a plain color

2021-03-21 06:08 UTC, jayasanka-sack requested changes
Good job @sathsarabandaraj !

The posts would come from their social media feed for now. So, let's remove that jeky'l part and replace it with a facebook embed. (we can embed amu page for demo purpose)

2021-04-11 12:54 UTC, Gimhan-minion approved these changes
The functionality looks good to me. @jayasanka-sack shall we use some kind of a plugin to auto-format the code? WDYT?

2021-04-11 13:02 UTC, jayasanka-sack approved these changes

2021-04-11 13:03 UTC, merged