Initiate history page
acf-sack/sack-site pull request #192
Opened 2021-04-25 16:48 UTC by kumuditha-udayanga

## Purpose

- The purpose of this PR is to fix #191 

## Goals

- Implement the history page using Jekyll.

## Approach

- Create a separate directory for the history page.
- Create a new layout for the history page and history-content page.
- Load the .md files in the _posts folder to the history page

### Screenshots

  https://user-images.githubusercontent.com/27630091/116001797-0944e980-a614-11eb-8f80-aae94116cee9.mov

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2021-04-29 16:12 UTC, jayasanka-sack requested changes
Thanks @kumuditha-udayanga !

i've added some review comments.

btw, shall we try to get rid of html in data pages?

the goal is to have a mechanism that anyone can update the data file easily without having an html knowledge.


Also the filenames of markdown files should be changed to the year. Ex: 2012.markdown.  (We can use .md instead of .markdown , btw)

2021-04-29 16:12 UTC, jayasanka-sack commented on _posts/2020-04-22-2002.markdown
> +layout: post
Shall we change the layout names? (Ex: history_page)

2021-04-29 16:12 UTC, jayasanka-sack commented on _posts/2020-04-22-2002.markdown
> +    <li>Vice Captain: Robert H. Anderson</li>
Is there a way to avoid having HTML, but only the data?

2021-04-29 16:12 UTC, jayasanka-sack commented on history/index.html
> +</div>
Let's add a new line

2021-05-16 16:41 UTC, kumuditha-udayanga commented
@jayasanka-sack, I've update the PR :)

2021-05-22 17:28 UTC, jayasanka-sack approved these changes
Thanks @kumuditha-udayanga !

2021-05-22 17:28 UTC, merged