Make the Navbar responsive
acf-sack/sack-site pull request #219
Opened 2021-08-15 15:30 UTC by Hasthikagirihagama

## Purpose

The purpose of this PR is to fix #218

## Goals

To make the navigation bar responsive

## Approach

Made the navigation bar responsive according to the screen size

### Screenshots

<img width="735" alt="Screenshot 2021-08-14 at 11 29 51" src="https://user-images.githubusercontent.com/70457601/129483446-90aa2db0-cc56-4902-a819-3e66ff736653.png">
<img width="733" alt="Screenshot 2021-08-15 at 20 47 51" src="https://user-images.githubusercontent.com/70457601/129483455-606e3077-ba3f-4e9f-8674-342c7d3051e3.png">
<img width="735" alt="Screenshot 2021-08-15 at 20 48 23" src="https://user-images.githubusercontent.com/70457601/129483464-d7f5836f-f590-4f19-8453-54a094e34f77.png">

  
### Preview Link
https://hasthikagirihagama.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2021-08-15 18:07 UTC, kumuditha-udayanga commented on index.html
> +
Remove this space

2021-08-15 18:08 UTC, kumuditha-udayanga commented on assets/css/custom.css
> +      box-shadow:
Take this to a oneline

2021-08-15 18:11 UTC, kumuditha-udayanga commented on _includes/static/navbar.html
> +          </div>
Format this part, the closing tag has an indentation issue.

2021-08-15 18:13 UTC, kumuditha-udayanga requested changes
Great Work! @Hasthikagirihagama 🥳, there are few changes.

2021-08-15 18:17 UTC, kumuditha-udayanga commented
@jayasanka-sack, There is a issue with the contact number component and the search component in the navbar in mobile view, any suggestions.

2021-08-15 18:22 UTC, kumuditha-udayanga commented on _includes/static/navbar.html
> +          </div>
Format this part, the closing tag has an indentation issue.

2021-08-16 03:46 UTC, Hasthikagirihagama commented on _includes/static/navbar.html
> +          </div>
yes what should I change in there?

2021-08-16 06:11 UTC, Hasthikagirihagama commented on assets/css/custom.css
> +      box-shadow:
It means should I remove this line ?

2021-08-17 18:09 UTC, kumuditha-udayanga commented on _includes/static/navbar.html
> +                </a></li>
@Hasthikagirihagama,In this line `</a> </li>` is in the same line. Break those closing tags into two lines and align with their open tag.

2021-08-17 18:14 UTC, kumuditha-udayanga commented on _includes/static/navbar.html
>                <li class="active nav-item"><a href="javascript:;" class="nav-link">Admission
In this line too, Break `<li>` and `<a>` break them into two lines. Always format the code before adding them. (Only the part that you add or change, not the whole code)

2021-08-17 18:27 UTC, kumuditha-udayanga requested changes
Always, select the part of the code you changed, and format it using (Shift + Option + F). Then all indentation issues will be automatically be fixed.

2021-09-09 18:29 UTC, Hasthikagirihagama commented
I think now the errors are fixed

2021-09-09 18:35 UTC, kumuditha-udayanga commented
@Hasthikagirihagama, Great work!, there's a small issue try to fix it
https://user-images.githubusercontent.com/27630091/132743160-4dd48aba-c127-48b4-90c3-2832a468ca00.mov

2021-09-18 04:04 UTC, jayasanka-sack commented
@kumuditha-udayanga Could you please review this again?

2021-09-19 17:33 UTC, kumuditha-udayanga approved these changes
Thank you @Hasthikagirihagama, amazing work!

2021-09-19 17:36 UTC, merged