Bursar page body for v5
acf-sack/sack-site pull request #221
Opened 2021-08-29 07:58 UTC by akeel230

## Purpose
fix issue #216 

## Goals
Implement the bursar page according to the following design.
https://www.figma.com/file/3nKwsfWXeZIwb21Hee8ZFL/SACK-Site?node-id=411%3A3368

## Approach
Made the bursar body manually

### Screenshots
![Screenshot (340)](https://user-images.githubusercontent.com/83522139/131242766-85c2ec42-8e89-4434-89fd-ed9416c02d93.png)

  
### Preview Link

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
none

## Test environment
Jekyll , Live server

## Learning
Jekyll

2021-08-30 09:14 UTC, sathsarabandaraj requested changes

2021-08-30 09:14 UTC, sathsarabandaraj commented on Gemfile
> +gem "webrick", "~> 1.7"
Why did you add 'webrick'. as I know webrick is also an HTTP server toolkit
We can use 'bundle exec jekyll server' to preview.
@kumuditha-udayanga please check this.

2021-08-30 09:14 UTC, sathsarabandaraj approved these changes

2021-08-30 10:28 UTC, kumuditha-udayanga commented on Gemfile
> +gem "webrick", "~> 1.7"
Actually in some(including my self) without webrick "bundle exec jekyll serve" wont work, but what I usually do is i don't add the gem files to my PR

2021-08-30 14:10 UTC, sathsarabandaraj commented on Gemfile
> +gem "webrick", "~> 1.7"
What if we add gem files to gitignore list.
We can use Dependabot to create PR if dependency update available.

2021-08-30 14:13 UTC, sathsarabandaraj commented
@akeel230 can you add preview link.
https://docs.github.com/en/pages

2021-08-31 06:54 UTC, kumuditha-udayanga commented on bursar/index.html
> +        <h2 class="mt-0 text-center"><button type="button" class="btn btn-info text-center font-weight-bold">See
Is this <h2> necessary?

2021-08-31 06:56 UTC, kumuditha-udayanga commented on bursar/index.html
> +            <p>
Remove the <p> tag opening and closing ones

2021-09-04 05:52 UTC, merged

2021-09-04 05:57 UTC, kumuditha-udayanga commented
Thank you @akeel230, awesome work!.