Navbar Button Hover
acf-sack/sack-site pull request #293
Opened 2022-01-06 02:01 UTC by Yoshitha-SACK

## Purpose

The purpose of this PR is to fix #<issue-number>

## Goals

## Approach

### Screenshots

  
### Preview Link

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-01-06 02:43 UTC, Yoshitha-SACK commented
Is it good ?

2022-01-06 13:56 UTC, Piumal1999 requested changes

2022-01-06 13:56 UTC, Piumal1999 commented on _includes/static/navbar.html
> +            <div class="col-sm-8" id="NavBtnHover">
Good job @Yoshitha-SACK!
We can do this with a CSS class instead of using an id. So we can reuse the style with every navbar link.

- Use `nav-btn-hover` or something like that as the class name (Here's a good article about CSS naming conventions: https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/ )
- Add it to the relevant items. Example: 
```
<li class="nav-item"><a href="../../" class="nav-link nav-btn-hover">Home</a></li>
```

2022-01-06 13:56 UTC, Piumal1999 commented on history/index.html
> +
Remove the unwanted line changes if possible

2022-01-07 02:33 UTC, Yoshitha-SACK commented
Can't do like that

2022-01-07 02:33 UTC, Yoshitha-SACK commented
It is not working

2022-01-07 03:29 UTC, Yoshitha-SACK commented
Ok

2022-01-07 03:37 UTC, Yoshitha-SACK commented on history/index.html
> +
Now is it ok

2022-01-07 03:38 UTC, Yoshitha-SACK commented
Now is it ok

2022-01-07 06:44 UTC, Piumal1999 approved these changes
Well done!!🤩 @Yoshitha-SACK 
Thank you very much

2022-01-07 06:46 UTC, merged