Change the colour of the phone number
acf-sack/sack-site pull request #318
Opened 2022-01-10 11:57 UTC by Yoshitha-SACK

## Purpose

The purpose of this PR is to fix ##300

## Goals

Changing the color of the phone number in the navbar.

## Approach

I made a class in navbar.html and custom.css file I add the color required.

### Screenshots

  
### Preview Link
https://yoshitha-sack.github.io/sack-site/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-01-10 13:00 UTC, Piumal1999 requested changes

2022-01-10 13:00 UTC, Piumal1999 commented on assets/css/custom.css
> +.phone-number {
Well done @Yoshitha-SACK.
Can you change the class according to this: https://github.com/acf-sack/sack-site/pull/308#issuecomment-1007891137

2022-01-10 17:47 UTC, kumuditha-udayanga commented
@Yoshitha-SACK  Thank you for your contribution,
This PR makes the contact numbers to the previous maroon colour according to the Preview.
Currently, the colour of the phone number in the navbar is correct.
Can you change the colour of the contact number at the bottom of the home page to the exact colour `#00316A` in the navbar in the hosted site?

2022-01-11 12:12 UTC, Yoshitha-SACK commented
> 

Ok I said it to the jayasanka ayya (issue - home page contact number). Is he told to change that?

2022-01-11 12:25 UTC, closed without merging