Update contact us page
acf-sack/sack-site pull request #351
Opened 2022-01-15 17:13 UTC by VishwaAmarasinghe

## Purpose

The purpose of this PR is to fix #338 

## Goals

tile should in left-aligned and same to other topic style

## Approach

### Screenshots
![image](https://user-images.githubusercontent.com/90438593/149630943-9ed5dc9d-f940-40cc-937b-2d398432ced2.png)

  
### Preview Link
https://vishwaamarasinghe.github.io/sack-site/
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-01-16 07:39 UTC, Piumal1999 commented
@VishwaAmarasinghe can you remove the ` pt-5 pb-5` part from the header section and ` pt-5` from the second section. (pb is padding bottom, pt is padding top). The padding is so large

![image](https://user-images.githubusercontent.com/27498587/149651379-a0c50fa8-d6b7-41ef-9b33-661f21a2a70e.png)

2022-01-16 07:52 UTC, VishwaAmarasinghe commented
> @VishwaAmarasinghe can you remove the ` pt-5 pb-5` part from the header section and ` pt-5` from the second section. (pb is padding bottom, pt is padding top). The padding is so large
> 
> ![image](https://user-images.githubusercontent.com/27498587/149651379-a0c50fa8-d6b7-41ef-9b33-661f21a2a70e.png)

Ok brother

2022-01-16 11:41 UTC, kumuditha-udayanga requested changes
Thank you @VishwaAmarasinghe, Change the title font to `Roboto` as in the hosted page.

2022-01-17 08:02 UTC, Piumal1999 commented
@VishwaAmarasinghe Please update the screenshot and approach section of the pull request description

2022-01-17 08:06 UTC, VishwaAmarasinghe commented
> 

Ok brother I did it

2022-01-17 11:49 UTC, kumuditha-udayanga commented
<img width="1632" alt="Screenshot 2022-01-17 at 5 18 06 PM" src="https://user-images.githubusercontent.com/27630091/149764405-a2c7432d-db73-4d7c-98c0-d1bc0f50b931.png">
@VishwaAmarasinghe shall we increase the margin between the "Contact Us" title and the map. WDYT @Piumal1999 ?

2022-01-17 11:59 UTC, Piumal1999 commented
> WDYT @Piumal1999 ?

Yeah. @VishwaAmarasinghe try adding `pt-5` class to the section. It will add a size-5 padding.

2022-01-17 12:12 UTC, VishwaAmarasinghe commented
Ok brother

2022-01-17 14:00 UTC, Yoshitha-SACK commented
> <img alt="Screenshot 2022-01-17 at 5 18 06 PM" width="1632" src="https://user-images.githubusercontent.com/27630091/149764405-a2c7432d-db73-4d7c-98c0-d1bc0f50b931.png">
> 
> @VishwaAmarasinghe shall we increase the margin between the "Contact Us" title and the map. WDYT @Piumal1999 ?

Yeah it is better but @kumuditha-udayanga if we put a margin to the contact map div the map will crached. I tried that (increasing the map margin).

2022-01-17 14:18 UTC, VishwaAmarasinghe commented
> > <img alt="Screenshot 2022-01-17 at 5 18 06 PM" width="1632" src="https://user-images.githubusercontent.com/27630091/149764405-a2c7432d-db73-4d7c-98c0-d1bc0f50b931.png">
> > @VishwaAmarasinghe shall we increase the margin between the "Contact Us" title and the map. WDYT @Piumal1999 ?
> 
> Yeah it is better but @kumuditha-udayanga if we put a margin to the contact map div the map will crached. I tried that (increasing the map margin).

I add pt-5 to heading and it's working

2022-01-17 14:24 UTC, kumuditha-udayanga commented
@VishwaAmarasinghe @Yoshitha-SACK take a look at this https://www.w3schools.com/css/css_grid.asp

2022-01-18 12:13 UTC, Piumal1999 approved these changes

2022-01-18 17:26 UTC, kumuditha-udayanga approved these changes
Good work @VishwaAmarasinghe, Keep it up.

2022-01-18 17:26 UTC, merged

2022-01-19 10:05 UTC, jayasanka-sack commented on assets/css/custom.css
> +
@kumuditha-udayanga @Piumal1999  I don't think we should introduce new font classes. 

The key principle is to leverage the UI Kit and bootstrap CSS as much as we could without introducing new classes. Otherwise, it damages the design consistency. 

As an example consider the fonts and fonts of the title page and the history page. They look totally different. We should stick to the [Material Kit's typography classes.](
https://demos.creative-tim.com/material-kit-bs4/#typography)

In this case, an ideal implementation would be `<h1 class="title">Contact us</h1>`

I think I have mentioned in the issue as well. 

cc: @VishwaAmarasinghe

2022-01-19 11:01 UTC, Piumal1999 commented on assets/css/custom.css
> +
> We should stick to the [Material Kit's typography classes.](https://demos.creative-tim.com/material-kit-bs4/#typography)

Ah right. Does it mean that we should use the same fonts in the Material Kit documentation? I thought we are using Roboto for every text.

2022-01-19 13:28 UTC, jayasanka-sack commented on assets/css/custom.css
> +
I think sticking into the material kit fonts would be ideal. If we need to change something that comes by default, then the best way is to regenerate the material CSS file using saas.

2022-01-19 13:30 UTC, jayasanka-sack commented on assets/css/custom.css
> +
@VishwaAmarasinghe Could you please send another PR removing the CSS class you created?

2022-01-19 15:13 UTC, VishwaAmarasinghe commented on assets/css/custom.css
> +
Ok @jayasanka-sack brother