Generate preview link for each PR
acf-sack/sack-site pull request #371
Opened 2022-01-17 14:17 UTC by kumuditha-udayanga

## Purpose

The purpose of this PR is to fix #349 #320

## Goals

- Generate a preview link for each Pull request.

## Approach

- Create a workflow to create a preview link for each Pull request.
- Update pull request template.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2022-01-17 15:22 UTC, jayasanka-sack requested changes
Shall we use acf@sack.edu.lk?

We should not use the admin account for any given reason.

2022-01-30 11:38 UTC, Piumal1999 commented
@kumuditha-udayanga is this PR ready for review?

2022-02-02 05:57 UTC, Piumal1999 commented on .github/workflows/main.yml
> +          DEPLOY_DOMAIN: https://pr-${{ github.event.number }}-sack-site-acf.surge.sh
@kumuditha-udayanga can we move these values to GitHub secrets?

2022-02-02 06:05 UTC, jayasanka-sack commented on .github/workflows/main.yml
> +          DEPLOY_DOMAIN: https://pr-${{ github.event.number }}-sack-site-acf.surge.sh
We can't github secrets are not available for PRs from forks

2022-02-02 06:06 UTC, jayasanka-sack approved these changes
Thanks for getting this done, @kumuditha-udayanga !

2022-02-02 06:06 UTC, merged