Update contact us page again
acf-sack/sack-site pull request #373
Opened 2022-01-21 04:42 UTC by VishwaAmarasinghe

## Purpose

The purpose of this PR is to fix ##351

## Goals
Make the heading correct.

## Approach
I remove the text-roboto CSS class and also I remove it from index.html file .

### Screenshots
![image](https://user-images.githubusercontent.com/90438593/150466981-f83dc058-e872-4996-a452-ae73e9ee0de9.png)

  
### Preview Link

https://vishwaamarasinghe.github.io/sack-site/contact_us/
##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-01-21 04:43 UTC, VishwaAmarasinghe commented
@jayasanka-sack  please give your idea.

2022-01-21 05:44 UTC, Piumal1999 commented
@VishwaAmarasinghe shall we use this pull request to complete https://github.com/acf-sack/sack-site/issues/359 as well?

2022-01-21 14:01 UTC, VishwaAmarasinghe commented
> @VishwaAmarasinghe shall we use this pull request to complete #359 as well?

Ok brother

2022-01-27 06:22 UTC, VishwaAmarasinghe commented
Is it okay now @Piumal1999 brother

2022-01-28 05:13 UTC, Piumal1999 requested changes
Good job! @VishwaAmarasinghe 
I requested some minor changes. Please fix those and re-request the review.

2022-01-28 05:13 UTC, Piumal1999 commented on contact_us/index.html
> +      <div class="col-sm-4 pb-3 pt-2">
```suggestion
      <div class="col-sm-4 pb-3">
```
I think we don't need this padding here. Any special reason for adding that?

2022-01-28 05:13 UTC, Piumal1999 commented on contact_us/index.html
>    <!-- //Header -->
Remove this line
```suggestion

```

2022-01-28 05:13 UTC, Piumal1999 commented on contact_us/index.html
> +        <p><a href="mailto:principal@sack.edu.lk " class="text-dark ">Email: principal@sack.edu.lk</a></p>
```suggestion
        <p><a href="mailto:principal@sack.edu.lk" class="text-dark">Email: principal@sack.edu.lk</a></p>
```
Remove these extra spaces. Same in line 31

2022-01-28 05:13 UTC, Piumal1999 commented on contact_us/index.html
> -  <div class="row google-map">
I think we can also remove the custom CSS related to this google-map.

2022-01-28 06:19 UTC, VishwaAmarasinghe commented on contact_us/index.html
> -  <div class="row google-map">
Ok brother

2022-01-28 06:29 UTC, VishwaAmarasinghe commented on contact_us/index.html
> +      <div class="col-sm-4 pb-3 pt-2">
Ok brother I will remove it. No special reason for adding this.

2022-01-30 04:03 UTC, VishwaAmarasinghe commented
Is it okay now @Piumal1999 brother

2022-01-30 11:34 UTC, Piumal1999 approved these changes
Brilliant! @VishwaAmarasinghe 
Thank you for getting this done

2022-01-30 11:36 UTC, merged