Add a hover effect to the links in the top of the acf page
acf-sack/sack-site pull request #427
Opened 2022-06-18 10:52 UTC by YoshithaRathnayake

## Purpose

The purpose of this PR is to fix #425 

## Goals

Adding a hover effect to the links in the top of the acf page

## Approach

  
### Preview Link

https://pr-427-sack-site-acf.surge.sh/acf

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-06-18 22:21 UTC, Piumal1999 requested changes

2022-06-18 22:21 UTC, Piumal1999 commented on assets/css/custom.css
> +.society-nav-link:hover, .society-nav-link.active:hover {
I think we already have a custom css class for that. 
Try using `nav-btn-hover` class with the tab. 

Example:
```
<li class="nav-item">
    <a class="society-nav-link nav-btn-hover" href="#google-classroom" data-toggle="tab">
        Google Classroom
    </a>
</li>
```

2022-06-20 02:29 UTC, YoshithaRathnayake commented on assets/css/custom.css
> +.society-nav-link:hover, .society-nav-link.active:hover {
Ok @YoshithaRathnayake done!

2022-06-22 17:23 UTC, Piumal1999 requested changes

2022-06-22 17:23 UTC, Piumal1999 commented on acf/index.html
>  								<div class="ripple-container"></div>
I think we can remove these ripple containers also. The ripple effect automatically comes with the links

2022-06-23 07:25 UTC, YoshithaRathnayake commented on acf/index.html
>  								<div class="ripple-container"></div>
Ok done @Piumal1999 !

2022-06-24 19:52 UTC, Piumal1999 approved these changes
Good job @YoshithaRathnayake 
Thank you!

2022-06-24 19:52 UTC, merged